//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLP
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int KhachHangID { get; set; }
        public string TEN { get; set; }
        public string DiaChi { get; set; }
        public int SoDienThoai { get; set; }
    
        public virtual Ve Ve { get; set; }
    }
}
