//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int VeID { get; set; }
        public bool TrangThai { get; set; }
        public int XuatChieuID { get; set; }
        public int PhongID { get; set; }
        public Nullable<int> GiaVe { get; set; }
        public Nullable<int> KhachHangID { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual XuatChieu XuatChieu { get; set; }
    }
}
